apiVersion: batch/v1
kind: Job
metadata:
  name: v0.14.0-upgrade
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.14.2"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: eventing-controller
      restartPolicy: Never
      containers:
      - name: upgrade-brokers
        image: registry.svc.ci.openshift.org/openshift/knative-v0.14.2:knative-eventing-upgrade-v0-14-0

---
